export const metadata = {
  title: 'Untwist knowledge hub',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        
        {/* <link rel="icon" href="/favicon.ico" sizes="any" /> */}
        <link rel="icon" href="https://www.untwist.eu/wp-content/uploads/2020/10/FAV-16.png" type="image/png" sizes="32x32"/>

      </head>
      <body>{children}</body>
    </html>
  )
}
